#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSiwgzipFt8JrzTyy7dWpPHjdbER53jdNqdS"
APP_SECRET: "nPyWuA9qu/xPbOISnqKw5YSbjwRKYu7aMVQZHntiGk2phDJkSzelsqL2u2f9cGc3vgnSv+92dR7poxpbPIM7Gl6wdUcGpPApxy/tT+VpB/xc78pxmTxejbM0xt0r8JFcuYPG9zt4c41uUOwKxc4W2gdZg4i9fkcNH/qZutlVJllkuoN0wwA="

#계좌번호 앞 8자리
CANO: "64098841"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"